// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh0Ojhn-D1XuL5s-IgIIYRC5Mg_tDV_xg',
    appId: '1:977217896728:web:20255eb394a1f3a9515e6d',
    messagingSenderId: '977217896728',
    projectId: 'uts-1125170135-login',
    authDomain: 'uts-1125170135-login.firebaseapp.com',
    storageBucket: 'uts-1125170135-login.firebasestorage.app',
    measurementId: 'G-PSP0DN27SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPA-EUQ3xgB3_2evtQ-2BFbgruBpusvMc',
    appId: '1:977217896728:android:862c6a25aee1d101515e6d',
    messagingSenderId: '977217896728',
    projectId: 'uts-1125170135-login',
    storageBucket: 'uts-1125170135-login.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh0Ojhn-D1XuL5s-IgIIYRC5Mg_tDV_xg',
    appId: '1:977217896728:web:65db0586a4e2bd98515e6d',
    messagingSenderId: '977217896728',
    projectId: 'uts-1125170135-login',
    authDomain: 'uts-1125170135-login.firebaseapp.com',
    storageBucket: 'uts-1125170135-login.firebasestorage.app',
    measurementId: 'G-PF3SZ402X9',
  );

}